using Xunit;

namespace AutoRegisterInject.Tests;

public partial class GenerationTests
{
    [Fact]
    public async Task ShouldGenerateInterfaceAndRegisterAsInterface()
    {
        const string INPUT = @"[AutoInterface]
[RegisterScoped]
public class Foo : IFoo
{
    public string Name { get; set; }
    public void Run(int count) { }
}";

        const string EXPECTED_REGISTRATION = @"// <auto-generated>
//     Automatically generated by AutoRegisterInject.
//     Changes made to this file may be lost and may cause undesirable behaviour.
// </auto-generated>
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

/// <summary>
/// AutoRegisterInject service collection extensions  
/// </summary>
public static class AutoRegisterInjectServiceCollectionExtension
{
    /// <summary>
    /// Adds all types registered with AutoRegisterInject attributes to the given
    /// service collection from the named assembly
    /// </summary>
    /// <param name=""serviceCollection"">Service collection to register types with</param>
    /// <returns>Service collection with registered types</returns>
    public static Microsoft.Extensions.DependencyInjection.IServiceCollection AutoRegisterFromTestProject(this Microsoft.Extensions.DependencyInjection.IServiceCollection serviceCollection)
    {
        return AutoRegister(serviceCollection);
    }

    /// <summary>
    /// Adds all types registered with AutoRegisterInject attributes to the given
    /// service collection
    /// </summary>
    /// <param name=""serviceCollection"">Service collection to register types with</param>
    /// <returns>Service collection with registered types</returns>
    internal static Microsoft.Extensions.DependencyInjection.IServiceCollection AutoRegister(this Microsoft.Extensions.DependencyInjection.IServiceCollection serviceCollection)
    {
        serviceCollection.AddScoped<IFoo, Foo>();
        return serviceCollection;
    }
}";

        const string EXPECTED_INTERFACE = @"// <auto-generated>
//     Automatically generated by AutoRegisterInject.
//     Changes made to this file may be lost and may cause undesirable behaviour.
// </auto-generated>
public interface IFoo
{
    string Name { get; set; }
    void Run(int count);
}";

        await RunGenerator(
            INPUT,
            EXPECTED_REGISTRATION,
            ("AutoRegisterInject.IFoo.g.cs", EXPECTED_INTERFACE));
    }

    [Fact]
    public async Task ShouldGenerateInterfaceInNamespace()
    {
        const string INPUT = @"namespace MyApp.Services;

[AutoInterface]
[RegisterTransient]
public class Foo : IFoo { }";

        const string EXPECTED_REGISTRATION = @"// <auto-generated>
//     Automatically generated by AutoRegisterInject.
//     Changes made to this file may be lost and may cause undesirable behaviour.
// </auto-generated>
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

/// <summary>
/// AutoRegisterInject service collection extensions  
/// </summary>
public static class AutoRegisterInjectServiceCollectionExtension
{
    /// <summary>
    /// Adds all types registered with AutoRegisterInject attributes to the given
    /// service collection from the named assembly
    /// </summary>
    /// <param name=""serviceCollection"">Service collection to register types with</param>
    /// <returns>Service collection with registered types</returns>
    public static Microsoft.Extensions.DependencyInjection.IServiceCollection AutoRegisterFromTestProject(this Microsoft.Extensions.DependencyInjection.IServiceCollection serviceCollection)
    {
        return AutoRegister(serviceCollection);
    }

    /// <summary>
    /// Adds all types registered with AutoRegisterInject attributes to the given
    /// service collection
    /// </summary>
    /// <param name=""serviceCollection"">Service collection to register types with</param>
    /// <returns>Service collection with registered types</returns>
    internal static Microsoft.Extensions.DependencyInjection.IServiceCollection AutoRegister(this Microsoft.Extensions.DependencyInjection.IServiceCollection serviceCollection)
    {
        serviceCollection.AddTransient<MyApp.Services.IFoo, MyApp.Services.Foo>();
        return serviceCollection;
    }
}";

        const string EXPECTED_INTERFACE = @"// <auto-generated>
//     Automatically generated by AutoRegisterInject.
//     Changes made to this file may be lost and may cause undesirable behaviour.
// </auto-generated>
namespace MyApp.Services
{

public interface IFoo
{

}
}";

        await RunGenerator(
            INPUT,
            EXPECTED_REGISTRATION,
            ("AutoRegisterInject.IFoo.g.cs", EXPECTED_INTERFACE));
    }
}
